server:
  port: 8080

spring:
  application:
    name: backend-starter
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework: INFO
    com:
      carlosrdev: DEBUG



